### PR TITLE
nix-script-store-plugin: add missing boost library

### PR DESCRIPTION
**Pull request by zimbatm**
this should fix the hydra evaluation

### CODE REVIEW

**Comment by zimbatm** [comment]
approving myself :D

**Comment by grahamc** [comment]
We probably even want to delete this plugin actually, since we don’t use it.

**Comment by grahamc** [comment]
Otherwise lgtm :)

**Comment by zimbatm** [comment]
Oh really :D I am just trying to make hydra green without understanding what is going on here :D

**Comment by puffnfresh** [comment]
Yeah delete it :+1:

**Pull request merged**
