### PR TITLE
update the Nix requirements

### PR DESCRIPTION
**Pull request by zimbatm**
Nix 2.0 is now available everywhere

### CODE REVIEW

**Comment by zimbatm** [comment]
I don't have a mac at hand to test the changes.

**Comment by periklis** [comment]
@zimbatm i will throw it on monday on our mac builder

**Comment by periklis** [comment]
i think the following line needs also an amend:
https://github.com/nix-community/linuxkit-nix/blob/master/release.nix#L3

**Comment by zimbatm** [comment]
fixed, thanks

**Pull request merged**
