### PR TITLE
Merge staging into master

### PR DESCRIPTION
**Pull request by nicknovitski**
As I noted in the other PR, I'm able to build everything locally, and the hydra set is now fully green. Is there anything blocking these updates?

### CODE REVIEW

**Comment by nicknovitski** [comment]
Hooray! 🎉

**Comment by zimbatm** [comment]
Thanks for all the hard work @nicknovitski!

Would you be interested in taking over the maintainership of this project?

**Comment by nicknovitski** [comment]
I would be.  Probably the first thing I'd try to do is get several of these packages into nixpkgs.

I'm a novice at rust, completely ignorant of ocaml, and most importantly, not that well-versed in virtualization and hypervisors.  But if that's alright, I do use the project and have the bandwidth for it.

**Comment by zimbatm** [comment]
Yes that's more than alright. You already contributed a lot of good things to the project that was essentially dormant before you arrived.

**Comment by zimbatm** [comment]
You should have received an invite to the org. Welcome!

**Pull request merged**
